---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Teams2Teams API prototype
  description: This is a simple API in case of try the login functions out.

servers:
  - url: http://localhost:8080/v1

tags:
  - name: LoginApi
    description: Login api consists of login and logout

paths:
  /login:
    post:
      tags:
        - LoginApi
      description: User login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successfully login and provided a session id
          content:
            application/json:
              schema:
                type: object
                required:
                  - session_id
                properties:
                  sessionId:
                    type: string
                    format: uuid
        '400':
          $ref: '#/components/responses/GeneralError'
          
  /logout/{session_id}:
    delete:
      tags:
        - LoginApi
      description: User logout
      operationId: logout
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully logout and deleted session id
        '400':
          $ref: '#/components/responses/GeneralError'
        '404':
          description: Session id not found 

components:
  responses:
    GeneralError:
      description: Invalid operation
      content:
        application/json:
          schema:
            type: object
            required:
              - error_code
              - error_message
            properties:
              error_code:
                type: integer
                format: int32
              error_message:
                type: string  
