---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Teams2Teams API prototype
  description: This is a simple API in case of try the login functions out.

servers:
  - url: http://localhost:8080/v1

tags:
  - name: Healthcheck
    description: The ping is the only one health check api
  - name: Authentication
    description: Authentication api consists of login and logout

paths:
  /ping:
    get:
      tags:
        - Healthcheck
      description: Check the system live status
      operationId: ping
      responses:
        '200':
          description: Everything is ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
        '400':
          $ref: '#/components/responses/GeneralError'

  /login:
    post:
      tags:
        - Authentication
      description: User login operation
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: Successfully login and provided a session id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginOutput'
        '400':
          $ref: '#/components/responses/GeneralError'
          
  /logout/{session_id}:
    delete:
      tags:
        - Authentication
      description: User logout operation
      operationId: logout
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully logout and deleted session id
        '400':
          $ref: '#/components/responses/GeneralError'
        '404':
          description: Session id not found 

components:

  schemas:
    Pong:
      type: object 
      required:
        - pong
      properties:
        pong:
          type: string

    LoginInput:
      type: object 
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          #format: password

    LoginOutput:
      type: object
      required:
        - session_id
      properties:
        sessionId:
          type: string
          format: uuid

    GeneralError:
      type: object
      required:
        - error_code
        - error_message
      properties:
        error_code:
          type: integer
          format: int32
        error_message:
          type: string

  responses:
    GeneralError:
      description: For any unexpected operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'

