swagger: '2.0'

info:
  version: 0.0.1
  title: Teams-2-Teams BE API
  description: Teams-2-Teams Backend API

host: tbd.com
basePath: /v1
schemes:
  - https
  - http

consumes:
  - application/json
produces:
  - application/json

paths:
  /user:
    get:
      description: Returns the list of users
      responses:
        '200':
          description: Successful response

    post:
      description: Creates a new user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/newUser'
          description: new user
      responses:
        '200':
          description: Successful response
          

definitions:
  newUser:
    description: a new user message
    properties:
      name:
        type: string
        description: name of the user
      jelszo:
        type: string
        description: password of the user
      bemutatkozas:
        type: string
        description: introduction text of the user
    required:
      - user
      - jelszo
      - bemutatkozas